Issue/140 hardware shop item specs
cryptic-game/frontend pull request #188
Opened 2020-10-02 23:43 UTC by SophieErdbeer

**Description**
> Added the technical specifications for the remaining hardware parts for the shop

**Issue**
Closes #140 

**Testing Instructions**
> For testing: Open the hardware shop and look at the now added technical specifications

**Additional Notes**
> none

2020-10-02 23:46 UTC, JannikEmmerich requested changes
Please setup your local Git installation correctly. Help can be found [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)

2020-10-02 23:51 UTC, MarcelCoding requested changes
Please format your code with the formatter of your IDE.

2020-10-03 00:14 UTC, MarcelCoding requested changes

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +import * as hardwareParts from '../../../../api/hardware/hardware-parts';
Remove `*` import

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +         return{
Reformat Code

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +        return{
Reformat Code

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +        return{
Reformat Code

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +        return{
Reformat Code

2020-10-03 00:14 UTC, MarcelCoding commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +        return{
Reformat Code

2020-10-03 00:15 UTC, JannikEmmerich approved these changes
Everything that has to do with Git looks fine to me, good job!
The code style can be improved in some places, wait for @MaxiHuHe04 to review for details.

2020-10-03 00:23 UTC, MarcelCoding approved these changes

2020-10-05 18:19 UTC, MaxiHuHe04 requested changes

2020-10-05 18:19 UTC, MaxiHuHe04 commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +            'Frequeny max': `${cpu.frequencyMax} MHz`,
Typos: Frequeny -> Frequency

2020-10-05 18:19 UTC, MaxiHuHe04 commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +        console.log(ram.ramTyp);
Remaining debug output

2020-10-05 18:19 UTC, MaxiHuHe04 commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +            'Type': mainboard.ram.ramTyp.map(type => type.join(' ')).join(', '),
Unlike Mimas said on Discord, DDRx is written without a space 😄

2020-10-05 18:19 UTC, MaxiHuHe04 commented on src/app/desktop/windows/hardware-shop/hardware-shop-item/hardware-shop-item.component.ts
> +            'Type': gpu.ramTyp.join(' '),
Unlike Mimas said on Discord, GDDRx is written without a space 😄

2020-10-08 20:07 UTC, MaxiHuHe04 approved these changes
Good job!

2020-10-08 20:10 UTC, merged