Version Pre-Alpha 2.0
cryptic-game/frontend pull request #210
Opened 2021-01-14 20:47 UTC by MaxiHuHe04

**Description**

## Additions:
- Computer hardware
- System for building computers
- System workload
- Task-manager app that displays system utilization
- Wallet app that displays balance and transactions
- Hardware-shop app to buy computer components
- File-manager app
- Settings app to set the wallpaper and terminal text color
- CPU miner app that generates in-game cryptocurrency
- Texteditor app
- Basic network system (currently only available in the terminal)
- New terminal commands
- Control-Center
- Base for hardware exchange among players
- Ability to shut down computers
- Ability to switch between computers
- Possibility to report bugs via a link in the start menu
- Changelog
- Progressive web app support and update indicator
- Ability to change the account password
- Ability to stop and delete services, exception: SSH (not available in the frontend yet)

## Enhancements:
- Computers disassembly while keeping the parts
- Login and registration, added a password strength indicator
- Filesystem with directories
- Improved commands in the terminal
- New app icon design

## Changes:
- Password requirements: no special characters, but instead one upper and lower case character
- Removed the browser app draft
- Removed email addresses at registration

## Fixes:
- Resizing of app windows
- Several bugs in the start menu and the terminal
- Miner app could be opened multiple times
- Many bugs in the frontend and backend

2021-01-14 20:52 UTC, JannikEmmerich approved these changes

2021-01-14 21:08 UTC, Defelo submitted a review, later dismissed

2021-01-14 21:11 UTC, MarcelCoding requested changes
Please move the IntelliJ Run Configuration into the `.run` folder: 

![image](https://user-images.githubusercontent.com/34819524/104649725-6f38e100-56b5-11eb-8307-5e37ea8b08c6.png)

2021-01-14 21:14 UTC, JannikEmmerich submitted a review, later dismissed

2021-01-14 21:21 UTC, DevMimas approved these changes

2021-01-14 22:06 UTC, Defelo approved these changes

2021-01-14 22:17 UTC, JannikEmmerich approved these changes

2021-01-14 22:20 UTC, DevMimas approved these changes

2021-01-14 22:48 UTC, MarcelCoding reviewed
Approved! Good work @MaxiHuHe04 @JannikEmmerich @Defelo @ClientCrash @Chaozz66 @SophieErdbeer @janekx21!
(These are all the participants, except me, of the pre-alpha 2 front end)

2021-01-15 10:47 UTC, Chaozz66 approved these changes

2021-01-15 11:23 UTC, merged