Updated Editor
cryptic-game/frontend pull request #227
Opened 2021-01-23 09:32 UTC by Tert0

**Description**
Added an "Edit" Feature to the Texteditor.
Added a deleted File Popup and changed File Popup to the Texteditor.

**Issue**
Closes #219 

**Testing Instructions**
- Open a file and Write something.
- Open a new Editor an open the same File.
- Save the Changes of the first Editor
- In the 2nd Editor should be a Popup.
- Now remove the File.
- Now should be an other Popup in both Editors

**Important**
You can destroy Wallets by Edit them!

2021-01-24 19:28 UTC, MarcelCoding requested changes

2021-01-24 19:28 UTC, MarcelCoding commented on src/app/desktop/windows/editor/editor.component.ts
> +
Please correct intentions

2021-01-25 06:57 UTC, JannikEmmerich requested changes

2021-01-25 06:57 UTC, JannikEmmerich commented on src/app/desktop/windows/editor/editor.component.ts
> +
Remove unnecessary line breaks.

2021-01-26 14:26 UTC, MarcelCoding approved these changes

2021-01-26 14:54 UTC, JannikEmmerich requested changes

2021-01-26 14:54 UTC, JannikEmmerich commented on src/app/desktop/windows/editor/editor.component.scss
> +    padding: 0px;
Add some padding so it looks better.
```suggestion
    padding: 5px;
```

2021-01-26 14:54 UTC, JannikEmmerich commented on src/app/desktop/windows/editor/editor.component.scss
>    }
Remove the outline of the text field.
```suggestion
    outline: none;
  }
```

2021-01-26 14:54 UTC, JannikEmmerich commented on src/app/desktop/windows/editor/editor.component.ts
> +
Remove empty line.
```suggestion

```

2021-01-26 15:13 UTC, MarcelCoding approved these changes

2021-01-26 15:14 UTC, JannikEmmerich approved these changes

2021-01-26 15:21 UTC, merged