Changed ls Sort and Styling
cryptic-game/frontend pull request #232
Opened 2021-01-23 22:18 UTC by Tert0

**Description**
Changed the Sort. of `ls`:
- Folder 
- Files

Folders are Blue.

**Issue**
Closes #231 

**Testing Instructions**
> Type in `ls` to the Terminal

2021-01-24 00:31 UTC, MarcelCoding approved these changes

2021-01-24 00:31 UTC, MarcelCoding commented on src/app/desktop/windows/terminal/terminal-states.ts
> +      this.fileService.getFiles(this.activeDevice['uuid'], this.working_dir).subscribe((files) => {
```suggestion
      this.fileService.getFiles(this.activeDevice['uuid'], this.working_dir).subscribe(files => {
```

2021-01-24 00:31 UTC, MarcelCoding commented on src/app/desktop/windows/terminal/terminal-states.ts
> +  }
Why don't you chain the operators instead of using a variable?

2021-01-24 07:59 UTC, Tert0 commented
Please dont aprove i got some Ideas from Chaozz and Mimas

2021-01-25 06:54 UTC, JannikEmmerich requested changes

2021-01-25 06:54 UTC, JannikEmmerich commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
This has noting to do with your pull request.

2021-01-25 06:54 UTC, JannikEmmerich commented on src/assets/api.json
> +  "url_test": "wss://ws.cryptic-game.net"
This has nothing to do with your pull request.

2021-01-25 07:59 UTC, Tert0 commented
@JannikEmmerich Changed it.

2021-01-25 07:59 UTC, Tert0 commented
> Please dont aprove i got some Ideas from Chaozz and Mimas

This PR is now Ready

2021-01-26 15:00 UTC, JannikEmmerich requested changes

2021-01-26 15:00 UTC, JannikEmmerich commented on src/app/desktop/windows/settings/settings.component.html
> +      <span>ls File/Folder Prefix</span>
```suggestion
      <span>`ls` command file/folder prefix</span>
```

2021-01-26 15:00 UTC, JannikEmmerich commented on src/app/desktop/windows/settings/settings.component.html
> +      <span>ls Folder Color</span>
```suggestion
      <span>`ls` folder color</span>
```

2021-01-26 15:00 UTC, JannikEmmerich commented on src/app/desktop/windows/settings/settings.service.ts
> +  // LS Folder color
```suggestion
  // ls command folder color
```

2021-01-26 15:00 UTC, JannikEmmerich commented on src/app/desktop/windows/settings/settings.service.ts
> +  // LS Prefix
```suggestion
  // ls command prefix
```

2021-01-26 15:00 UTC, JannikEmmerich commented on src/app/desktop/windows/terminal/terminal-states.ts
>      if (args.length === 0) {
```suggestion
  ls(args: string[]) {
    if (args.length === 0) {
```

2021-01-26 15:00 UTC, JannikEmmerich commented on src/assets/api.json
> +  "url": "wss://ws.test.cryptic-game.net"
```suggestion
  "url": "wss://ws.test.cryptic-game.net/"
```

2021-01-26 15:08 UTC, JannikEmmerich approved these changes

2021-01-26 15:08 UTC, MarcelCoding approved these changes

2021-01-26 15:28 UTC, merged