Added theme colors
cryptic-game/frontend pull request #272
Opened 2021-09-12 20:21 UTC by ClientCrash

**Description**
This PR creates a scss file with all theme colors from 
#260

2021-09-13 13:22 UTC, ClientCrash commented
@MaxiHuHe04

2021-09-13 17:18 UTC, Akida31 commented
probably link #273 instead of #272 in PR description

2021-09-18 12:49 UTC, MarcelCoding requested changes

2021-09-18 12:49 UTC, MarcelCoding commented on src/app/design/_theme-colors.scss
> +$primary-disabled:#2E473E;
```suggestion
$primary-disabled: #2E473E;
```

2021-09-18 12:49 UTC, MarcelCoding commented on src/app/design/_theme-colors.scss
> +$success-disabled:#2F5629;
```suggestion
$success-disabled: #2F5629;
```

2021-09-18 12:49 UTC, MarcelCoding commented on src/app/design/_theme-colors.scss
> +$warning-disabled:#675926;
```suggestion
$warning-disabled: #675926;
```

2021-09-18 12:49 UTC, MarcelCoding commented on src/app/design/_theme-colors.scss
> +$danger-disabled:#671E35;
```suggestion
$danger-disabled: #671E35;
```

2021-09-18 12:49 UTC, MarcelCoding commented on src/app/design/_theme-colors.scss
> +$info-disabled:#2D456C;
```suggestion
$info-disabled: #2D456C;
```

2021-09-18 12:51 UTC, MarcelCoding submitted a review, later dismissed

2021-09-19 12:50 UTC, MarcelCoding requested changes

2021-09-19 12:50 UTC, MarcelCoding commented on src/styles.scss
> +@import "theme-colors";
If you don't use it, don't include it.

2021-09-19 12:53 UTC, MarcelCoding commented
You removed the changes from these comments: https://github.com/cryptic-game/frontend/pull/272/files/32d31bc8a871f63743e608d9e573070497bec3b4

2021-09-19 13:35 UTC, ClientCrash commented
> You removed the changes from these comments: https://github.com/cryptic-game/frontend/pull/272/files/32d31bc8a871f63743e608d9e573070497bec3b4

I made changes. @MarcelCoding

2021-09-19 13:46 UTC, MarcelCoding approved these changes

2021-09-21 14:19 UTC, ClientCrash commented
@MarcelCoding please request a review from @MaxiHuHe04

2021-10-06 19:09 UTC, Tert0 approved these changes

2021-10-06 19:11 UTC, ClientCrash commented
@MaxiHuHe04 is still requested for review. @MarcelCoding can you remove the review request i asked for?

2021-10-06 20:23 UTC, ClientCrash commented
@cryptic-game/head-of-frontend @cryptic-game/head-assistant-of-frontend

2021-12-19 13:20 UTC, ClientCrash commented
@MaxiHuHe04

2022-02-28 08:53 UTC, merged