Updated to Angular 13
cryptic-game/frontend pull request #314
Opened 2022-02-14 15:15 UTC by MarcelCoding

**Description**
Based on #291.

**Issue**
Closes #270

**TODO**
- [ ] Remove depriction
- [ ] Cleanup typescript types
- [ ] Improve eslint rules
- [ ] Remove https://github.com/cryptic-game/frontend/blob/ng13/tsconfig.json#L25-L27

2022-02-17 15:18 UTC, Tristan-H11 requested changes

2022-02-17 15:18 UTC, Tristan-H11 commented on src/app/account/account-page-base/account-page-base.component.ts
> +    // Starting from 1.19.0 you can add custom presets or shape here, using the current tsParticles instance (main)
```suggestion
```

2022-02-17 15:18 UTC, Tristan-H11 commented on src/app/account/account-page-base/account-page-base.component.ts
> +    console.log(container);
```suggestion
```

2022-02-17 15:46 UTC, Tristan-H11 submitted a review, later dismissed

2022-02-20 18:27 UTC, Tristan-H11 commented
@MarcelCoding mergeee :D

2022-02-20 18:34 UTC, MarcelCoding commented
I don't have the permission to push into master.

2022-02-20 20:11 UTC, Tristan-H11 commented
@Defelo we want to merge. Can you help us? :)

2022-03-06 09:42 UTC, Tristan-H11 submitted a review, later dismissed

2022-03-06 11:07 UTC, merged