#323 also save wrong commands
cryptic-game/frontend pull request #324
Opened 2022-02-18 21:02 UTC by TimJ0212

**Description**
> Terminal commands are now stored in the history not after, but before the correctness check.

**Issue**
Closes #323 

**Testing Instructions**
> Type e.g. `help` (an existing command) into the terminal followed by a non-existing e.g. `test`. By pressing the up arrow, `test` should now appear in the terminal.

**Additional Notes**
> Reminder: UI/UX improvement due to imitation of a real terminal.

2022-02-18 23:55 UTC, TimJ0212 commented
Sorry, commit on wrong branch.
Feel free to review @all

2022-02-19 09:28 UTC, Tristan-H11 requested changes

2022-02-19 09:28 UTC, Tristan-H11 commented on src/app/desktop/windows/terminal/terminal-states.ts
> +    this.protocol.unshift(command);
```suggestion
    // Add command to protocol
    if (!this.commands[command].hideFromProtocol) {
      this.protocol.unshift(command);
    }
```
As there are some (and will be some more) easter egg commands, it is important to have to possibility of not logging some commands.

2022-02-19 09:40 UTC, Tristan-H11 approved these changes

2022-02-19 09:48 UTC, closed without merging